rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Position Controllers ---------------------------------------
  rotation_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: rotation_base
    pid: {p: 100.0, i: 0.10, d: 0.01}
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder
    pid: {p: 100.0, i: 0.10, d: 0.01}      
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.10, d: 0.01}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 10.0, i: 0.10, d: 0.01}
  joint_cam_position_controller:
    type: effort_controllers/JointPositionController
    joint: camera_joint
    pid: {p: 1.0, i: 0.10, d: 0.0001}